project:
  type: website
  output-dir: _site

website:
  title: "Dinesh Rawal"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume / CV
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: default
    css: styles.css
    toc: false
    page-layout: full
